sudo: required

before_install:
- .travis/oracle/download.sh
- .travis/oracle/install.sh

script:
- node index.js

notifications:
  email:
  - lebretr@gmail.com

language: node_js

node_js:
- '0.10'
- '0.12'

branches:
  only:
  - master

cache:
  directories:
  - node_modules

after_script:
- echo toto

env:
  global:
    - ORACLE_LOGIN_ssousername=esus62@gmail.com
    - secure: iiXpVKiy551p4d5Eh0nyScsKtuxGCuooEKkRcjoVOqhi0sWA5r201MjRulOwGCbgwEjDTS0X/Af5u9pAnv1Xe0vgZ4tK+ex2ax8hJI1tXcDH3Kbi/bZba3oG2ijv054yfWJgoBiVwFplKdogYmvEFB7WV5A7TgETKDX8ghKMGQFVi+eJfClQQIavlDY0dE/JMNAV6bpNrKwo31nM9dSE5InYaB9aONNHa95uVT1k2qYFCO9hmKDJbCg2XncdV3SASvsvDbWvzBP7ubakigVs1VXS5pIx1ixzqnNeeqDJ7HYRg9J6T8EgDuiPC1mL6lvx+gymtExqfbJ80wlkd59yFuIzac8B44xRT6hr3ZClqhjfwqzwovGPKUz5KoD9XyBsPA0++dFLvOhzx4VpgiL27RYQ6wJDByhNlOk5EpZpkw2e4Bn/jwrsMwCOFZ7NY5qrzuk+37PIHcmDc8sdW77L4o5Dg/cS2sKlwB67Y7w7VUPWOUdXGg0X8bXSljp4nv/0cWMzjoFF70jKjOmo7Q1TqWx1r9woEsG+qwVmR+WPBIj7sQJNwWT+WIlwNMbRXc1rVgg2X99keubKkzeshjfPjo9vjdHlieTDdFlWRXskl3BFhIstnKkuERBzjEZ+8u567f0n3hTAdA9toDfWIHs9HTItduMGcJ1oPkmRdiW4fNg=
    - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
